### ISSUE TITLE
Error message on 4.7.7

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#13]
CRM_Core_Exception: Cannot set unrecognized property CRM_Core_Config::$CiviPostCodeLookupProvider in CRM_Core_Config_MagicMerge->__set() (line 285 of /www/demo/sites/all/modules/civicrm/CRM/Core/Config/MagicMerge.php).

**Comment by tapashdatta** [comment]
This extension causes 4.7 upgrade to crash. Upgrade only works if extension is completely uninstalled beforehand.

**Comment by lsmithgo** [comment]
Any update on this?  The extension does not work at all on 4.7

**Comment by veda-consulting** [comment]
We've released a new version today to our own git directory, it should get
pushed later today or tomorrow

Veda Consulting
t : +44 (0) 20 3239 1156
m : +44 (0) 77 4216 3491
e : parvez@vedaconsulting.co.uk
w : www.vedaconsulting.co.uk
