### ISSUE TITLE
This Extension prevents Manual Contribution because of a Syntax Error

### ISSUE THREAD

**Issue by aashish108** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#20]
Hi,

With this extension enabled, I was unable to process a manual contribution against a contact via bank trf option. As soon as I choose bank trf option, the save and other buttons get disabled and do not get re-enabled.

I traced it back to your extension at postcodelookup.tpl, this was the issue (or the first error anyway, not sure if it was the main cause but disabling your extension made the issue go away):

In TPL:
`var locationTypes = {/literal}{$civiPostCodeLookupLocationTypeJson}{literal};`

Via DevTools, the above line shows up as:
`var locationTypes = ;`

**Comment by mattwire** [comment]
Hi or #19 has recently been merged and fixes this.  You can also go into postcode setting and tick all location types to fix it

**Comment by aashish108** [comment]
Oh cool - but it isn;'t available via CiviCRM extension update? I'll take a look at those settings. Cheers

**Comment by veda-consulting** [comment]
@aashish108 yeah we're looking to get it into the automatic update cycle.

**Comment by aashish108** [comment]
Hi, is this fixed in that 1.5 release that automatically came on CiviCRM?

**Comment by mattwire** [comment]
@aashish108 Yes

**Comment by aashish108** [comment]
Cheers!
