### ISSUE TITLE
Possible to add new postcode provider?

### ISSUE THREAD

**Issue by TomCrawshaw** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#22]
Hi folks,

great effort so far, but I wonder if it would be possible/easy to add another provider, getAddress (getaddress.io/)? I've looked through your code, but expertise is too limited to work out how to adapt.
Regards

**Comment by mattwire** [comment]
Looks pretty good as a provider, and seems to support county field too! @TomCrawshaw Are you able to offer funding to Veda for this?

**Comment by TomCrawshaw** [comment]
I think it's unlikely I could get funding for this, unless it was very little - postcode lookup is currently a "nice to have" (i.e. not considered essential) for us, plus, as a very small charity we are entitled to the free Royal Mail files, and if the CiviPostcode service worked efficiently this would be our preferred option.

**Comment by veda-consulting** [comment]
Hey Tom

Whats the issue your facing with *CiviPostcode?*

**Comment by TomCrawshaw** [comment]
Hi Parvez

There are a few practical niggles with the download & extraction process (I use a Mac, the Royal Mail file comes as an exe file which has to be extracted on a Windows box, & uploading is a slow manual process). Once uploaded, the new file does not appear to become available (I understand it take you a while to load it), and even searching test data (e.g. YO1 0) the initial response is too slow to be acceptable (i.e. around 20 secs), when it appears, the list of addresses isn’t scrollable (OSX, Chrome on Civi 4.7.23 on Drupal), and it takes another 20 secs or so to respond to a selection.

Compared to the almost instant response on commercial sites, this doesn’t really work well enough. If the response time was better, then we would cope with the download, extraction & upload process...

Best wishes

Tom

**Comment by mattwire** [comment]
@TomCrawshaw See #23 and #30

**Comment by mattwire** [comment]
Fixed via #30
