### ISSUE TITLE
Version 1.5 + php 7.1 

### ISSUE THREAD

**Issue by michael-chaplin-gmcvo** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#32]
Version 1.5 + php 7.1 gives an error:

Error: Using $this when not in object context in CRM_Civicrmpostcodelookup_Page_Postcode::getPostcode() (line 14 of /home/*********/public_html/sites/default/files/civicrm/extensions/uk.co.vedaconsulting.module.civicrmpostcodelookup-1.1/CRM/Civicrmpostcodelookup/Page/Postcode.php).

Dropping php back to 5.6 fixes this. Given that we all have to move off php5.6 by the end of the year, please could you investigate soon?

Thanks Mike Chaplin

**Comment by mattwire** [comment]
Please test release 1.6 and close this issue if it is fixed?

**Comment by michael-chaplin-gmcvo** [comment]
Looks good - checking with end user - thanks for the speedy response.

M
