### ISSUE TITLE
New - Permission required to use postcode lookup

### ISSUE THREAD

**Issue by TomCrawshaw** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#34]
Not a bug, but I have just discovered that after upgrading to v1.6 I now need to set Drupal permissions for Post Code lookup, otherwise Anonymous users are denied access. Apologies if I've not spotted this in readme etc... New code in civicrmpostcodelookup.php:

/**
 * Implementation of hook_civicrm_permission
 *
 * @param array $permissions
 * @return void
 */
function civicrmpostcodelookup_civicrm_permission(&$permissions) {
  $prefix = ts('CiviCRM') . ': '; // name of extension or module
  $permissions += array(
    'access postcode lookup' => $prefix . ts('Access CiviCRM Postcode lookups'),
  );
}

**Comment by mattwire** [comment]
@TomCrawshaw Correct. You used to require "Access CiviEvent" to do anonymous lookups which was a bit random!

**Comment by mattwire** [comment]
Resolved by https://github.com/veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup/commit/a110de8c28d5e841ea9d5006568a72bac07ba95e
