### ISSUE TITLE
Search doesnt bring any result on PHP 7+

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#35]
No result comes when changed to php 7+. I am using postcodeanywhere. Ho can i solve this Please? thanks

**Comment by mattwire** [comment]
Civipostcode works on php7+. Are you using the latest release? It is possible there is an incompatibility with postcodeanywhere in this extension but it would be helpful if you could confirm another provider works first?

**Comment by tapashdatta** [comment]
I have just verified with civipostcode api. on php 5.6 search works on both civicrm 4.7 & 5.10 but doesnt work on php 7+ on either of the Civi versions.

**Comment by mattwire** [comment]
Civipostcode definitely works for me on PHP7.2.  Are you using civipostcode 1.6?  And, if you just upgraded did you enable the `Access CiviCRM Postcode lookups` permission for anyone who should be able to do postcode lookup?

If it still does not work, what error are you seeing in the logs?

**Comment by tapashdatta** [comment]
this is what I get in PHP error log

 `Notice: Undefined variable: addresslist in CRM_Civicrmpostcodelookup_Page_PostcodeAnywhere::search() (line 68 of /home/webadmin/public_html/cmm/sites/default/files/civicrm/ext/uk.co.vedaconsulting.module.civicrmpostcodelookup/CRM/Civicrmpostcodelookup/Page/PostcodeAnywhere.php).`

`Warning: simplexml_load_file(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in CRM_Civicrmpostcodelookup_Page_PostcodeAnywhere::search() (line 55 of /home/webadmin/public_html/cmm/sites/default/files/civicrm/ext/uk.co.vedaconsulting.module.civicrmpostcodelookup/CRM/Civicrmpostcodelookup/Page/PostcodeAnywhere.php).`

`Warning: simplexml_load_file(http://services.postcodeanywhere.co.uk/PostcodeAnywhere/Interactive/Find/v1.10/xmla.ws?Key=ABCD-EFGH_IJKL&UserName=+ISK1110014&SearchTerm=E78JG): failed to open stream: no suitable wrapper could be found in CRM_Civicrmpostcodelookup_Page_PostcodeAnywhere::search() (line 55 of /home/webadmin/public_html/cmm/sites/default/files/civicrm/ext/uk.co.vedaconsulting.module.civicrmpostcodelookup/CRM/Civicrmpostcodelookup/Page/PostcodeAnywhere.php).`

`Warning: simplexml_load_file(): I/O warning : failed to load external entity "http://services.postcodeanywhere.co.uk/PostcodeAnywhere/Interactive/Find/v1.10/xmla.ws?Key=ABCD-EFGH_IJKL&UserName=+ISK1110014&SearchTerm=E78JG" in CRM_Civicrmpostcodelookup_Page_PostcodeAnywhere::search() (line 55 of /home/webadmin/public_html/cmm/sites/default/files/civicrm/ext/uk.co.vedaconsulting.module.civicrmpostcodelookup/CRM/Civicrmpostcodelookup/Page/PostcodeAnywhere.php)`

**Comment by mattwire** [comment]
@tapashdatta That's a server issue - looks like you have a different config for PHP 5.x and 7.x as allow_url_fopen=0 on php7.x but it needs to be enabled for this extension to work.
