### ISSUE TITLE
Search result not in order

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#36]
We were using CIviPostcode api, but issue is result doesn't show all the address in an order. I have tried E7 8JG, IG2 7BY, N22 8NQ, result comes all mixed up!!

<img width="494" alt="Screenshot 2019-03-19 at 20 52 23" src="https://user-images.githubusercontent.com/5366545/54641027-12544b80-4a89-11e9-818e-ee527a203758.png">
<img width="434" alt="Screenshot 2019-03-19 at 20 51 59" src="https://user-images.githubusercontent.com/5366545/54641030-12544b80-4a89-11e9-9a14-5e72984a3bf4.png">
<img width="561" alt="Screenshot 2019-03-19 at 20 51 44" src="https://user-images.githubusercontent.com/5366545/54641031-12544b80-4a89-11e9-81f3-65fec003a807.png">
<img width="390" alt="Screenshot 2019-03-19 at 20 53 06" src="https://user-images.githubusercontent.com/5366545/54641033-12ece200-4a89-11e9-9da7-3e83a3de3534.png">

**Comment by mattwire** [comment]
@tapashdatta Please can you re-open at https://lab.civicrm.org/extensions/ukpostcodes/issues thanks
