### ISSUE TITLE
part address is getting removed when filling in

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#37]
I have noticed it for many other addresses but an example here... flat is missing.

<img width="200" alt="Screenshot 2019-05-17 at 12 10 31" src="https://user-images.githubusercontent.com/5366545/57924509-2ce64d80-789d-11e9-9958-86fb5fa5c5b9.png">
<img width="200" alt="Screenshot 2019-05-17 at 12 10 18" src="https://user-images.githubusercontent.com/5366545/57924510-2ce64d80-789d-11e9-8df1-b00d6e651e72.png">

another postcode tw3 1ta

**Comment by mattwire** [comment]
Which postcode service are you using?

**Comment by tapashdatta** [comment]
postcodeanywhere

**Comment by tapashdatta** [comment]
...also multiple lines of address seems to be merging into 1 line

**Comment by mattwire** [comment]
@tapashdatta I don't think we're seeing this anywhere else.  Are you able to test with another provider (eg. getaddress.io has a free plan for testing).

**Comment by pradpnayak** [comment]
@tapashdatta can you try this [PR](https://github.com/veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup/pull/38/files)?

**Comment by mattwire** [comment]
Resolved in 1.7
