### ISSUE TITLE
Get 'Invalid postcode' every time

### ISSUE THREAD

**Issue by clarkac1** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#39]
Installs of this extension using 'GetAddress()' now get 'Invalid postcode' every time.  Nothing has changed except Civi release levels which are both at 5.19.4. GetAddress() website is active and working so problem seems to be with extension.

**Comment by clarkac1** [comment]
Not 100% certain, but this might be because getaddress.io have now set their  'free' plan to expire after 30 days. i.e. After 30 days it stops working. I will confirm when I'm sure this is the case

**Comment by mattwire** [comment]
@clarkac1 If this is still an issue please reopen at https://lab.civicrm.org/extensions/ukpostcodes/issues
