### ISSUE TITLE
Autofill does not fill the "Street Address" and leaves blank on the v1.1

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#6]

**Comment by rajeshrhino** [comment]
@tapashdatta We are not able to reproduce the issue. 

Could you please provide the below information for further investigation? 
1. Your CiviCRM version
2. In which form the autofill does not fill the 'Street Address'? Is it add/edit contact form or online event/contribution/profile form?

**Comment by tapashdatta** [comment]
@rajeshrhino 
I am on CiviCRM 4.6.5 and it does not work on either of the form you mentioned. I have just found, its an issue with Safari browser. I am on Mac OS X 10.10.4.

I have tried with chrome browser and it seems fine though. So, not sure if you would consider this an issue!!!

**Comment by lawsy87** [comment]
I am getting the same issue, I am also not getting the county come through, or if the address has a house name etc. I am using civicrm 4.6.5 as well.

**Comment by veda-consulting** [comment]
@lawsy87 could you confirm if its working on other browsers?

**Comment by lawsy87** [comment]
Hi,

This has been tested on:

Mac:
Firefox
Chrome
Safari

Windows:
Firefox
Chrome
Safari

Postcode: CB6 2EN. Should return house name, road, town, county, country.

**Comment by rajeshrhino** [comment]
@lawsy87 

We have tested in all browsers in both Mac and Windows and the autofill is working as expected.

Could you test this in our demo site http://civi.intdms.com/civicrm/profile/create?gid=1&reset=1 and see if it works

Additional Info:
1. County field is not populated as county is not included in the PAF file. Please refer to royal mail developer guide ( http://www.royalmail.com/sites/default/files/docs/pdf/programmers_guide_edition_7_v5.pdf ) - Page 17
2. Country field is also not auto-filled during lookup, as PAF data applies only for UK postcodes. Country can be set to 'United Kingdom' as default in CiviCRM.

**Comment by lawsy87** [comment]
The demo you gave me provides me with the same as what I get on my installation. However, doing a vardump of the information that is given back from postcodeanywhere contains county:

array (size=1)
  '@attributes' => 
    array (size=30)
      'Udprn' => string '4073459' (length=7)
      'Company' => string '' (length=0)
      'Department' => string '' (length=0)
      'Line1' => string 'Head Fen Cottage' (length=16)
      'Line2' => string 'Head Fen' (length=8)
      'Line3' => string 'Pymoor' (length=6)
      'Line4' => string '' (length=0)
      'Line5' => string '' (length=0)
      'PostTown' => string 'Ely' (length=3)
      'County' => string 'Cambridgeshire' (length=14)
      'Postcode' => string 'CB6 2EN' (length=7)
      'Mailsort' => string '55141' (length=5)
      'Barcode' => string '(CB62EN1AW)' (length=11)
      'Type' => string 'Residential' (length=11)
      'DeliveryPointSuffix' => string '1A' (length=2)
      'SubBuilding' => string '' (length=0)
      'BuildingName' => string 'Head Fen Cottage' (length=16)
      'BuildingNumber' => string '' (length=0)
      'PrimaryStreet' => string 'Head Fen' (length=8)
      'SecondaryStreet' => string '' (length=0)
      'DoubleDependentLocality' => string '' (length=0)
      'DependentLocality' => string 'Pymoor' (length=6)
      'PoBox' => string '' (length=0)
      'PrimaryStreetName' => string 'Head' (length=4)
      'PrimaryStreetType' => string 'Fen' (length=3)
      'SecondaryStreetName' => string '' (length=0)
      'SecondaryStreetType' => string '' (length=0)
      'CountryName' => string 'England' (length=7)
      'CountryISO2' => string 'GB' (length=2)
      'CountryISO3' => string 'GBR' (length=3)

array (size=6)
  'id' => string '4073459.00' (length=10)
  'street' => string 'Head Fen Cottage, Head Fen' (length=26)
  'locality' => string 'Pymoor' (length=6)
  'town' => string 'Ely' (length=3)
  'postcode' => string 'CB6 2EN' (length=7)
  'county' => string 'Cambridgeshire' (length=14)

**Comment by lawsy87** [comment]
Hi there,

Just dropping a note to see if this has been picked up, want to use this for a client who is due to go live soon and they are really pestering for county to be updated with addresses.

Also, I have just updated to 1.1, I was using 1.0 which I modified to include house name myself. 1.1 does not include house name when using postcode anywhere results. Please see screenshot attached.

Cheers
![screen shot 2015-07-29 at 12 42 10](https://cloud.githubusercontent.com/assets/1449060/8956583/42702efe-35ef-11e5-9fa7-9eaf2b748255.png)

**Comment by veda-consulting** [comment]
@lawsy87 can you confirm that your not using the CiviPostcode but instead using PostcodeAnywhere with the extension? From our end we've been amending the extension to work better in line with CiviPostcode service, which is free under certain conditions. This is why your seeing the differences in the v1.1.

For us to debug and help with PostcodeAnywhere we really could do with a test account if you have one?

**Comment by veda-consulting** [comment]
@lawsy87 p.s. could you report as a new issue? The original issue has morphed into this one and they are actually referring to two different products.
