### ISSUE TITLE
Certain postcode shows error message, although the address exist

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#7]
I have came across few postcode which returns error message on the result screen. One of them is WD25 8EZ. I had few more but can't remember them now...
![image](https://cloud.githubusercontent.com/assets/5366545/8880163/7a9d146e-322e-11e5-9f37-0f58bf4640b2.jpg)

**Comment by rajeshrhino** [comment]
@tapashdatta Should work fine if you try with space in the postcode. 

![postcodelookup](https://cloud.githubusercontent.com/assets/1202659/8911912/1a8022fa-3487-11e5-829e-933fb9138c26.jpg)

**Comment by tapashdatta** [comment]
@rajeshrhino Seems its a bug with the postcode anywhere API service. Now that I have civipostcode service available, I confirm, its working fine as you have instructed. Thanks.

**Comment by veda-consulting** [comment]
Thanks @tapashdatta closing
