### ISSUE TITLE
Cannot upload CSV PAF on civipostcode website

### ISSUE THREAD

**Issue by tapashdatta** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#8]
I have downloaded PAF from royal mail. After extracting the CSV becomes 2GB in size. On civipostcode website, it only allows to upload 500MB. What is the solution please?

**Comment by rajeshrhino** [comment]
@tapashdatta You need to zip the PAF CSV file and upload the zipped file, as the original PAF CSV file is too large.

**Comment by tapashdatta** [comment]
@rajeshrhino thanks!! it worked now.
