### ISSUE TITLE
Issues with postcode anywhere

### ISSUE THREAD

**Issue by lawsy87** [veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup#9]
Continuing from:
https://github.com/veda-consulting/uk.co.vedaconsulting.module.civicrmpostcodelookup/issues/6

I am using postcode anywhere and not civipostcode. 

I can give you access to the stage site I have setup for my client at the minute if you ping me an email address or phone number to contact you on?

My email address is scott.mokler@pharma-mix.com

Cheers

**Comment by lawsy87** [comment]
Any luck looking into this? I sent over the API details but have had no response.

Cheers

**Comment by lawsy87** [comment]
Hey guys,

Any idea on progress on this?

Scott

**Comment by veda-consulting** [comment]
Hi Scott

Sorry, we’ve been busy on other projects recently. We’d hope to take a look mid week next week.

Thanks

**Comment by lawsy87** [comment]
Looking into moving to civipostcode... does this work or is there issues with this as well? I need a solution this week as client is waiting.

With civipostcode, I can see where I can get a sample PAF file from on the royal mail site but not the full file, could you assist at all?

**Comment by aydun** [comment]
You need to register to get the full PAF - http://www.poweredbypaf.com/register-for-free-use-of-paf/
For more info see http://civipostcode.com/docs

**Comment by lawsy87** [comment]
THanks - I am investigating this.

Any idea when the postcode-anywhere integration will be resolved?

**Comment by lawsy87** [comment]
THanks, I have looked into this and this could prove to be quite costly. We already have an api and account with postcode anywhere so this would be the ideal solution.

Please could you give us an ETA on the postcode anywhere integration issue being resolved. This is getting qute critical for us now as out client is wanting to launch their product but need this working to be able to do so.

**Comment by lukehudsonrx** [comment]
Hi, we have been experiencing a similar problem whilst using the plugin and civicrm, it's having a huge knock on effect for our members- any ideas when this can be resolved?

**Comment by cozmicdad** [comment]
Same problem here.
Postcode Anywhere is by far the most cost-effective solution for small businesses - paying for the PAF file is not an option for us.  Please get this fixed ASAP.

**Comment by neilwatson27** [comment]
Having installed postcode anywhere a couple of days ago it appears I have the same issue.
Is there a fix?

**Comment by veda-consulting** [comment]
Hi All - for those of you that meet the minimum requirements PAF sign up from the Royal Mail is effectively free so this is the lowest cost option.

For those using Postcode Anywhere we're looking to get a fix in the new few days, however longer term I would urge you to move to civipostcode as over time the service will grow to include many other other functions. For instance it currently provide geolocation services without limit, unlike google or yahoo.

**Comment by lawsy87** [comment]
Royal mail want to charge us £5000 per year for a licence to do what we want to do. Postcode anywhere is our only option really.

**Comment by lukehudsonrx** [comment]
Hi, when you said fixed in the next few days, does that mean by Friday this week, or Monday Tuesday next week? We have had this problem for over a month and it seems it was raised back in July by another user on here.

**Comment by veda-consulting** [comment]
@lukehudsonrx as your probably aware this is an open source element of the system which we support. I understand the issue has been open for over a month, if your able to either devote some time or alternatively some funding making it a priority is difficult. As it stands we're aiming to have this resolved in the new few working days. Hope that makes sense.

**Comment by lawsy87** [comment]
How much are we talking about here? I have been waiting a month for you guys to fix this. Yes it is open source and you have paid projects to work on, but this is the only plugin for postcode lookups for postcode anywhere in civicrm so kind of need to get it going.

**Comment by lukehudsonrx** [comment]
@veda-consulting thanks, and I do appreciate that it is open source, and that is the reason why we are using it, however as this is your product you do have a responsibility for its support and up keep, chances are as customers using one for your free products that works will mean we are more likely to pay for something in the future, but being asked to pay to fix something that is given for free is slightly concerning for us.

**Comment by veda-consulting** [comment]
@lawsy87 its a half days work to make the changes and test for both CiviPostcode and Postcode Anywhere, and then release back into the Extensions directory.

@lukehudsonrx we didn't ask for payment to fix it, simply that if its a priority then you could fund the fix or even take a look yourselves. All open source models are built in the same way as I'm sure your aware.

It'd be good to get back to the point of the thread, there is an issue, we are aware of it and our current timeline is to have it resolved in the next few working days. I can't be anymore precise then that right now as we have commitments for CiviCon next week as well as our existing queue of projects.

**Comment by veda-consulting** [comment]
@lawsy87 @lukehudsonrx and all. The issues should now be resolved. I'm closing this issue, if it still occurs or there are some odd cases then please create new issues with as much information as possible, Thanks
